### PR TITLE
Added new PCH API support and fixed a bug

### PR DESCRIPTION
**Pull request by nrodday**
1) PCH changed its API. I implemented the downloader for the new API and recreate the old format such that code that extracts data from those files later on can still be used.
2) The subnet extraction was not working correctly with the bugfix. The subnet position is the 7th in the file, not the 6th. After the bugfix, no subnets were extracted anymore. Instead, I increased the check before by 1 and moved the index back to the 7th position.

### CODE REVIEW

**Comment by nrodday** [comment]
https://github.com/gnomikos/traIXroute/issues/27

**Comment by slowr** [comment]
Thanks a lot for the PR!
I will take a look to see if the data are parsed as expected

**Comment by nrodday** [comment]
Hi Dimitrios,

Sure!

I want to use traixroute within my current tool chain, basically I would
like to hand over a trace in Python and get a result back from
traixroute whether it contains an IXP path, or not.

I could parse the output that I get from traixroute and map it back to
the original file but that seems silly, given that both, my toolchain as
well as traixroute, are written in Python. Also, the json output seems
to be non-compliant: https://github.com/gnomikos/traIXroute/issues/29

Do you know an easy way to call traixroute from another Python script
such that I can have it analyze a single trace and return a result that
I can directly continue to work with?

Thanks!

Cheers,
Nils





Am 05/09/2020 um 16:46 schrieb Dimitrios Mavrommatis:

**Comment by slowr** [comment]
Hi @nrodday , the easiest way to achieve what you want would be to call it with a subprocess and parse the output from it.

This should work: https://docs.python.org/3/library/subprocess.html#subprocess.check_output

**Review by slowr — APPROVED** [review]

**Pull request merged**
